/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2001'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2001'));
  } else {
    // Browser globals (root is window)
    if (!root.NineToFiveApi) {
      root.NineToFiveApi = {};
    }
    root.NineToFiveApi.AnnouncementsList = factory(root.NineToFiveApi.ApiClient, root.NineToFiveApi.InlineResponse2001);
  }
}(this, function(ApiClient, InlineResponse2001) {
  'use strict';

  /**
   * The AnnouncementsList model module.
   * @module model/AnnouncementsList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AnnouncementsList</code>.
   * @alias module:model/AnnouncementsList
   * @class
   * @extends Array
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AnnouncementsList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnnouncementsList} obj Optional instance to populate.
   * @return {module:model/AnnouncementsList} The populated <code>AnnouncementsList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'InlineResponse2001');
    }
    return obj;
  }

  Object.setPrototypeOf(exports.prototype, new Array());

  return exports;

}));
