/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NineToFiveApi) {
      root.NineToFiveApi = {};
    }
    root.NineToFiveApi.Profile = factory(root.NineToFiveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Profile model module.
   * @module model/Profile
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Profile</code>.
   * @alias module:model/Profile
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Profile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Profile} obj Optional instance to populate.
   * @return {module:model/Profile} The populated <code>Profile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('profileid'))
        obj.profileid = ApiClient.convertToType(data['profileid'], 'Number');
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'Number');
      if (data.hasOwnProperty('fullname'))
        obj.fullname = ApiClient.convertToType(data['fullname'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('about'))
        obj.about = ApiClient.convertToType(data['about'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} profileid
   */
  exports.prototype.profileid = undefined;

  /**
   * @member {Number} age
   */
  exports.prototype.age = undefined;

  /**
   * @member {String} fullname
   */
  exports.prototype.fullname = undefined;

  /**
   * @member {String} city
   */
  exports.prototype.city = undefined;

  /**
   * @member {String} gender
   */
  exports.prototype.gender = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} about
   */
  exports.prototype.about = undefined;


  return exports;

}));
