/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NineToFiveApi) {
      root.NineToFiveApi = {};
    }
    root.NineToFiveApi.RequestCreation = factory(root.NineToFiveApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RequestCreation model module.
   * @module model/RequestCreation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestCreation</code>.
   * @alias module:model/RequestCreation
   * @class
   * @param seekerUsername {String} 
   * @param providerUsername {String} 
   * @param jobTitle {String} 
   */
  var exports = function(seekerUsername, providerUsername, jobTitle) {
    this.seekerUsername = seekerUsername;
    this.providerUsername = providerUsername;
    this.jobTitle = jobTitle;
  };

  /**
   * Constructs a <code>RequestCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestCreation} obj Optional instance to populate.
   * @return {module:model/RequestCreation} The populated <code>RequestCreation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('seekerUsername'))
        obj.seekerUsername = ApiClient.convertToType(data['seekerUsername'], 'String');
      if (data.hasOwnProperty('providerUsername'))
        obj.providerUsername = ApiClient.convertToType(data['providerUsername'], 'String');
      if (data.hasOwnProperty('JobTitle'))
        obj.jobTitle = ApiClient.convertToType(data['JobTitle'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} seekerUsername
   */
  exports.prototype.seekerUsername = undefined;

  /**
   * @member {String} providerUsername
   */
  exports.prototype.providerUsername = undefined;

  /**
   * @member {String} jobTitle
   */
  exports.prototype.jobTitle = undefined;


  return exports;

}));
