/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body3', 'model/Body4', 'model/InlineResponse2003'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body3'), require('../model/Body4'), require('../model/InlineResponse2003'));
  } else {
    // Browser globals (root is window)
    if (!root.NineToFiveApi) {
      root.NineToFiveApi = {};
    }
    root.NineToFiveApi.ProfileApi = factory(root.NineToFiveApi.ApiClient, root.NineToFiveApi.Body3, root.NineToFiveApi.Body4, root.NineToFiveApi.InlineResponse2003);
  }
}(this, function(ApiClient, Body3, Body4, InlineResponse2003) {
  'use strict';

  /**
   * Profile service.
   * @module api/ProfileApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ProfileApi. 
   * @alias module:api/ProfileApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addProfile operation.
     * @callback module:api/ProfileApi~addProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new profile to the system.
     * FR - A registered user must be able to create a new profile. 
     * @param {Number} userid The userid of the user that submits a new profile.
     * @param {module:model/Body3} body Profile object that is going to be submited.
     * @param {module:api/ProfileApi~addProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.addProfile = function(userid, body, callback) {
      var postBody = body;

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling addProfile");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addProfile");
      }


      var pathParams = {
        'userid': userid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/user/{userid}/profile', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getProfile operation.
     * @callback module:api/ProfileApi~getProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View a certain profile
     * FR - A registered user must be able to view every profile. 
     * @param {Number} userid The userid of the user that view someone's profile.
     * @param {String} profileid The ID of the profile that is beeing viewed.
     * @param {module:api/ProfileApi~getProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.getProfile = function(userid, profileid, callback) {
      var postBody = null;

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling getProfile");
      }

      // verify the required parameter 'profileid' is set
      if (profileid === undefined || profileid === null) {
        throw new Error("Missing the required parameter 'profileid' when calling getProfile");
      }


      var pathParams = {
        'userid': userid,
        'profileid': profileid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/user/{userid}/profile/{profileid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateProfile operation.
     * @callback module:api/ProfileApi~updateProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Profile
     * FR - A registered user must be able to edit his own profile. 
     * @param {Number} userid The userid of the user that edit his profile.
     * @param {Number} profileid The ID of the profile that is updated.
     * @param {module:model/Body4} body Profile model
     * @param {module:api/ProfileApi~updateProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.updateProfile = function(userid, profileid, body, callback) {
      var postBody = body;

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling updateProfile");
      }

      // verify the required parameter 'profileid' is set
      if (profileid === undefined || profileid === null) {
        throw new Error("Missing the required parameter 'profileid' when calling updateProfile");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateProfile");
      }


      var pathParams = {
        'userid': userid,
        'profileid': profileid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/user/{userid}/profile/{profileid}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
