/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NineToFiveApi);
  }
}(this, function(expect, NineToFiveApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NineToFiveApi.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('addUser', function() {
        it('should call addUser successfully', function(done) {
          // TODO: uncomment, update parameter values for addUser call and complete the assertions
          /*
          var body = new NineToFiveApi.Body();
          body.username = "";
          body.password = "";

          instance.addUser(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NineToFiveApi.InlineResponse200);
            expect(data.userid).to.be.a('number');
            expect(data.userid).to.be("0");
            expect(data.username).to.be.a('string');
            expect(data.username).to.be("");
            expect(data.password).to.be.a('string');
            expect(data.password).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
