/*
 * NineToFive API
 * This is NineToFive API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ndummatt@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NineToFiveApi);
  }
}(this, function(expect, NineToFiveApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RequestCreation', function() {
      beforeEach(function() {
        instance = new NineToFiveApi.RequestCreation();
      });

      it('should create an instance of RequestCreation', function() {
        // TODO: update the code to test RequestCreation
        expect(instance).to.be.a(NineToFiveApi.RequestCreation);
      });

      it('should have the property seekerUsername (base name: "seekerUsername")', function() {
        // TODO: update the code to test the property seekerUsername
        expect(instance).to.have.property('seekerUsername');
        // expect(instance.seekerUsername).to.be(expectedValueLiteral);
      });

      it('should have the property providerUsername (base name: "providerUsername")', function() {
        // TODO: update the code to test the property providerUsername
        expect(instance).to.have.property('providerUsername');
        // expect(instance.providerUsername).to.be(expectedValueLiteral);
      });

      it('should have the property jobTitle (base name: "JobTitle")', function() {
        // TODO: update the code to test the property jobTitle
        expect(instance).to.have.property('jobTitle');
        // expect(instance.jobTitle).to.be(expectedValueLiteral);
      });

    });
  });

}));
