name : CI/CD

on : push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download deps
        run: npm i

      - name: Run tests
        run: npm run test

  cd: 
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ...... #Tokens of service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # [TODO] Create Token and put on github secret

        
      
