name: CI/CD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download deps
        run: npm i

      - name: Run tests
        run: npm run test

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/matt'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service e04bc5c0-d7be-42eb-86d6-16b4d810b75f
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
