name: CI/CD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download deps
        run: npm i

      - name: Run tests
        run: npm run test

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service 82bc2290-fbfa-47c4-9260-5dcbd384f6c0
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
